'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,X} from 'lucide-react';
type InstallEvent=Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export function InstallApp(){const [open,setOpen]=useState(false),[installed,setInstalled]=useState(false),[ready,setReady]=useState(false);const event=useRef<InstallEvent|null>(null),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{setInstalled(window.matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator & {standalone?:boolean}).standalone));const prompt=(e:Event)=>{e.preventDefault();event.current=e as InstallEvent;setReady(true);};const done=()=>{setInstalled(true);setOpen(false);event.current=null;};window.addEventListener('beforeinstallprompt',prompt);window.addEventListener('appinstalled',done);return()=>{window.removeEventListener('beforeinstallprompt',prompt);window.removeEventListener('appinstalled',done);};},[]);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
 async function install(){if(!event.current)return;await event.current.prompt();const choice=await event.current.userChoice;event.current=null;setReady(false);if(choice.outcome==='accepted')setOpen(false);}
 if(installed)return null;return <><button className="install-app" onClick={()=>setOpen(true)}><Download size={18}/>Instalar aplicación</button><dialog ref={dialog} className="modal install-dialog" onCancel={()=>setOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setOpen(false);}}><div className="modal-header"><h2>CCA SECTOR 7 en tu teléfono</h2><button autoFocus aria-label="Cerrar instrucciones" onClick={()=>setOpen(false)}><X/></button></div><p>Abrí la aplicación desde un ícono en la pantalla de inicio.</p>{ready&&<button className="mission-add full" onClick={()=>void install()}>Instalar en este dispositivo</button>}<h3>Android</h3><p>Abrí este enlace en Chrome. En el menú ⋮, elegí “Instalar aplicación” o “Agregar a la pantalla de inicio”.</p><h3>iPhone</h3><p>Abrí este enlace en Safari. Tocá Compartir y luego “Agregar a la pantalla de inicio”.</p><p className="helper">Si estás dentro de otra aplicación, abrí el enlace en el navegador del teléfono. El ingreso actual y la conexión a internet siguen siendo necesarios.</p></dialog></>;
}
