'use client';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,Plus} from 'lucide-react';
import {weekDates,shiftWeek} from '../lib/week';
import {sectorsOf} from '../lib/sectors';
type Item={id:string;date:string;start?:string;end?:string;sector?:string;sectors?:string[];sectors_json?:string|null;service?:string;guests?:number;place?:string;place_id?:string;person_ids?:string[];people?:string[];notes?:string;title?:string};
export function WeekAgenda({module,selected,onSelect,sector='',place='',person='',revision}:{module:'kitchen'|'missions';selected:string;onSelect:(date:string)=>void;sector?:string;place?:string;person?:string;revision?:unknown}){
 const dates=weekDates(selected),start=dates[0]||'';const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!start)return;const controller=new AbortController();setLoading(true);setError('');const months=[...new Set(weekDates(start).map(d=>d.slice(0,7)))];async function load(){try{const parts=await Promise.all(months.map(async month=>{const r=await fetch((module==='kitchen'?'/api/reservations':'/api/missions')+'?month='+month,{cache:'no-store',signal:controller.signal});const data=await r.json() as Item[] & {error?:string};if(!r.ok)throw new Error(data.error||'No pudimos cargar la semana.');return data;}));if(!controller.signal.aborted){setItems(parts.flat());setError('');}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'No pudimos cargar la semana.');}finally{if(!controller.signal.aborted)setLoading(false);}}void load();const timer=setInterval(()=>void load(),30000);return()=>{controller.abort();clearInterval(timer);};},[start,module,retry,revision]);
 const fmt=(date:string,options:Intl.DateTimeFormatOptions)=>new Date(date+'T12:00:00Z').toLocaleDateString('es-AR',{...options,timeZone:'UTC'});
 const filtered=items.filter(r=>module==='kitchen'?(!sector||sectorsOf({...r,sector:r.sector||''}).includes(sector)):(!place||r.place_id===place)&&(!person||r.person_ids?.includes(person)));
 return <section className="week-agenda" aria-label="Agenda semanal"><div className="week-heading"><button aria-label="Semana anterior" onClick={()=>onSelect(shiftWeek(selected,-1))}><ChevronLeft size={20}/></button><h2>{start&&fmt(start,{day:'numeric',month:'short'})} — {dates[6]&&fmt(dates[6],{day:'numeric',month:'short',year:'numeric'})}</h2><button aria-label="Semana siguiente" onClick={()=>onSelect(shiftWeek(selected,1))}><ChevronRight size={20}/></button></div>{loading&&<p className="loading" role="status">Cargando semana…</p>}{error&&<div className="error" role="alert">{error}<button onClick={()=>setRetry(v=>v+1)}>Reintentar</button></div>}{!loading&&!error&&dates.map(date=>{const day=filtered.filter(r=>r.date===date);return <button key={date} className={'week-day '+(date===selected?'selected':'')} aria-pressed={date===selected} onClick={()=>onSelect(date)}><span className="week-date">{fmt(date,{weekday:'long'})}<strong>{fmt(date,{day:'numeric',month:'short'})}</strong></span><span className="week-items">{day.length?day.map(r=><span className={'week-event '+(module==='missions'?'mission':r.service==='food'?'food':'space')} key={r.id}><strong>{module==='missions'?r.place:r.title}</strong><span>{module==='missions'?r.people?.join(' + '):`${r.start}–${r.end} · ${r.sector}`}</span>{module==='kitchen'&&<span>{r.guests} {r.service==='food'?'comensales':'personas · solo espacio'}</span>}{r.notes&&<span className="week-note">{r.notes}</span>}</span>):<span className="week-empty">{module==='missions'?'Sin atenciones':'Sin reservas'} <Plus size={16}/></span>}</span></button>;})}<p className="helper week-help">Tocá un día para consultar su detalle o agregar una actividad.</p></section>;
}
