import {sectorsOf,type SectorRecord} from './sectors';
export type AlmanacRow=SectorRecord&{id:string;date:string;title:string;start:string;end:string;guests:number;service:string};
export function calendarCells(month:string){const first=new Date(month+'-01T12:00:00Z');const offset=(first.getUTCDay()+6)%7;return Array.from({length:42},(_,i)=>{const d=new Date(first);d.setUTCDate(1-offset+i);return d.toISOString().slice(0,10);});}
export function almanacJpg({mode,period,name,rows,module='kitchen'}:{mode:'month'|'year';period:string;name:string;rows:AlmanacRow[];module?:'kitchen'|'missions'}):string{
 const canvas=document.createElement('canvas');canvas.width=mode==='month'?3508:2480;canvas.height=mode==='month'?2480:3508;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('No pudimos preparar el almanaque en este dispositivo.');
 const W=canvas.width,H=canvas.height,M=100;ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);const ink='#153c50',muted='#617989',line='#d6e2e8';
 function font(size:number,bold=false){ctx!.font=`${bold?'700':'400'} ${size}px Arial, sans-serif`;}
 function fit(text:string,width:number){if(ctx!.measureText(text).width<=width)return text;let value=text;while(value.length&&ctx!.measureText(value+'…').width>width)value=value.slice(0,-1);return value+'…';}
 function text(value:string,x:number,y:number,size:number,color=ink,bold=false,width=W-2*M){font(size,bold);ctx!.fillStyle=color;ctx!.fillText(fit(value,width),x,y);}
 function wrap(value:string,width:number,max=2){const words=value.split(/\s+/);const lines:string[]=[];let part='';for(const word of words){const candidate=part?part+' '+word:word;if(ctx!.measureText(candidate).width>width&&part){lines.push(part);part=word;if(lines.length===max-1)break;}else part=candidate;}if(lines.length===max-1){const consumed=lines.join(' ').length;lines.push(fit(value.slice(consumed).trim(),width));}else if(part)lines.push(fit(part,width));return lines;}
 const indexed=new Map<string,AlmanacRow[]>();for(const r of rows){const group=indexed.get(r.date)||[];group.push(r);indexed.set(r.date,group);}for(const group of indexed.values())group.sort((a,b)=>a.start.localeCompare(b.start));
 text(name,M,155,mode==='month'?62:56,ink,true);text(mode==='month'?new Date(period+'-01T12:00:00Z').toLocaleDateString('es-AR',{month:'long',year:'numeric',timeZone:'UTC'}):'Almanaque '+period,M,mode==='month'?250:238,mode==='month'?82:78,ink,true);
 const mission=module==='missions';const noun=mission?'atenciones':'reservas';const meals=rows.filter(r=>r.service==='food');text(mission?`${rows.length} atenciones misioneras`:`${rows.length} reservas · ${meals.reduce((n,r)=>n+r.guests,0)} comensales con comida`,M,mode==='month'?319:305,34,muted);
 const week=['LUN','MAR','MIÉ','JUE','VIE','SÁB','DOM'];
 if(mode==='month'){
  const x=M,y=420,w=W-2*M,cellW=w/7,cellH=290;
  week.forEach((day,i)=>text(day,x+i*cellW+16,y-27,32,muted,true));
  calendarCells(period).forEach((date,i)=>{const col=i%7,row=Math.floor(i/7),cx=x+col*cellW,cy=y+row*cellH;ctx.fillStyle=date.slice(0,7)!==period?'#f6f8fa':col>4?'#fafcfd':'#fff';ctx.fillRect(cx,cy,cellW,cellH);ctx.strokeStyle=line;ctx.lineWidth=2;ctx.strokeRect(cx,cy,cellW,cellH);if(date.slice(0,7)!==period)return;text(String(Number(date.slice(-2))),cx+15,cy+45,36,ink,true,cellW-30);const events=indexed.get(date)||[];events.slice(0,2).forEach((r,j)=>{const ey=cy+66+j*94;ctx.fillStyle=mission?'#eaf4ed':r.service==='food'?'#fff0de':'#eaf1f8';ctx.fillRect(cx+10,ey,cellW-20,88);const color=mission?'#32664a':r.service==='food'?'#93561d':'#356784';text(mission?r.title:`${r.start}–${r.end} · ${r.guests} ${r.service==='food'?'com.':'pers.'}`,cx+18,ey+23,25,color,true,cellW-36);font(27,true);const labels=wrap(sectorsOf(r).join(' + '),cellW-36,2);labels.forEach((s,k)=>text(s,cx+18,ey+49+k*28,27,color,true,cellW-36));});if(events.length>2)text(`+${events.length-2} ${noun} más`,cx+14,cy+278,24,muted,false,cellW-28);});
  text(mission?'Cada atención indica el lugar y los hermanos que viajan. +N indica más atenciones.':'Comida: naranja · Solo espacio: azul · +N indica más reservas en ese día.',M,H-165,29,muted);
  text(mission?'Los viajes misioneros se organizan sin reservar la cocina.':'Las cantidades son el total de todos los sectores de cada reserva.',M,H-110,29,muted);
 }else{
  const gap=34,blockW=(W-2*M-gap*2)/3,blockH=715,y=382;
  for(let n=0;n<12;n++){const month=period+'-'+String(n+1).padStart(2,'0');const x=M+(n%3)*(blockW+gap),top=y+Math.floor(n/3)*(blockH+26);text(new Date(month+'-01T12:00:00Z').toLocaleDateString('es-AR',{month:'long',timeZone:'UTC'}),x,top+45,47,ink,true,blockW);const cw=blockW/7,ch=86,gy=top+115;week.forEach((d,i)=>text(d,x+i*cw+9,gy-14,25,muted,true,cw-12));calendarCells(month).forEach((date,i)=>{const cx=x+(i%7)*cw,cy=gy+Math.floor(i/7)*ch;ctx.strokeStyle=line;ctx.lineWidth=1;ctx.strokeRect(cx,cy,cw,ch);if(date.slice(0,7)!==month)return;const events=indexed.get(date)||[];if(events.length){ctx.fillStyle='#e6f1f7';ctx.fillRect(cx+1,cy+1,cw-2,ch-2);}text(String(Number(date.slice(-2))),cx+10,cy+34,31,ink,!!events.length,cw-16);if(events.length){text(String(events.length),cx+12,cy+67,26,'#17627b',true,cw-22);ctx.fillStyle=events.some(r=>r.service==='food')?'#c57329':'#608eae';ctx.fillRect(cx+cw-20,cy+55,9,9);}});const count=rows.filter(r=>r.date.startsWith(month)).length;text(`${count} ${noun}`,x,top+blockH-12,27,muted,false,blockW);}
  text(mission?'Días coloreados: con atención · Número pequeño: cantidad de atenciones.':'Días coloreados: ocupados · Número pequeño: cantidad de reservas.',M,H-125,29,muted);
  text(mission?'El almanaque mensual muestra los lugares y los hermanos asignados.':'Naranja: incluye comida · Azul: solo espacio. El mensual muestra sectores y horarios.',M,H-72,26,muted);
 }
 return canvas.toDataURL('image/jpeg',0.94);
}
