import type {MissionEntry,MissionTrip} from './missions';
export function weekendDates(month:string){const first=new Date(month+'-01T12:00:00Z');const dates:string[]=[];for(let n=1;n<=31;n++){const d=new Date(first);d.setUTCDate(n);if(d.toISOString().slice(0,7)!==month)break;if(d.getUTCDay()===0||d.getUTCDay()===6)dates.push(d.toISOString().slice(0,10));}return dates;}
export function missionWeekendJpg({month,name,places,trips}:{month:string;name:string;places:MissionEntry[];trips:MissionTrip[]}){
 const canvas=document.createElement('canvas');canvas.width=3508;canvas.height=2480;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('No pudimos preparar la planilla.');const M=100,W=canvas.width,H=canvas.height,dates=weekendDates(month),labelWidth=510,cellWidth=(W-2*M-labelWidth)/dates.length,top=400,headerHeight=125;ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);
 function font(size:number,bold=false){ctx!.font=`${bold?'700':'400'} ${size}px Arial, sans-serif`;}
 function fit(value:string,width:number){if(ctx!.measureText(value).width<=width)return value;let s=value;while(s.length&&ctx!.measureText(s+'…').width>width)s=s.slice(0,-1);return s+'…';}
 function text(value:string,x:number,y:number,size:number,width:number,bold=false){font(size,bold);ctx!.fillStyle='#153c50';ctx!.fillText(fit(value,width),x,y);}
 function lines(value:string,width:number,max:number,size:number,bold=false){font(size,bold);if(max<=1)return [fit(value,width)];const result:string[]=[];let current='';const words=value.split(/\s+/);for(let i=0;i<words.length;i++){const next=current?current+' '+words[i]:words[i];if(ctx!.measureText(next).width>width&&current){result.push(current);current=words[i];if(result.length>=max-1){result.push(fit(words.slice(i).join(' '),width));return result;}}else current=next;}if(current)result.push(fit(current,width));return result.slice(0,max);}
 // Notes are wrapped completely, including long words, rather than shortened.
 function fullLines(value:string,width:number){font(32);const result:string[]=[];for(const paragraph of value.split(/\r?\n/)){let current='';for(const ch of paragraph){if(ctx!.measureText(current+ch).width>width&&current){const split=current.lastIndexOf(' ');if(split>0){result.push(current.slice(0,split));current=current.slice(split+1)+ch;}else{result.push(current);current=ch;}}else current+=ch;}result.push(current);}return result;}
 const noted=trips.filter(t=>t.notes.trim()&&places.some(p=>p.id===t.place_id)).sort((a,b)=>a.date.localeCompare(b.date)||a.place.localeCompare(b.place)||a.id.localeCompare(b.id));
 const noteBlocks=noted.map((t,i)=>({id:t.id,number:i+1,lines:fullLines(`[${i+1}] ${t.date.slice(8,10)}/${t.date.slice(5,7)} · ${t.place}: ${t.notes.trim()}`,W-2*M)}));
 const notesHeight=noteBlocks.length?65+noteBlocks.reduce((sum,b)=>sum+b.lines.length*39+12,0):0;
 const rowHeight=Math.min(230,(H-top-headerHeight-220-notesHeight)/Math.max(places.length,1));
 if(rowHeight<80)throw new Error('Las observaciones completas no entran en una hoja A4. Elegí una localidad para imprimirla por separado o acortá los textos.');
 text(name+' / Viajes Misioneros',M,145,59,W-2*M,true);text(new Date(month+'-01T12:00:00Z').toLocaleDateString('es-AR',{month:'long',year:'numeric',timeZone:'UTC'})+' · Atenciones por localidad',M,240,66,W-2*M,true);text('Sábados y domingos · Hermanos asignados',M,313,34,W-2*M);
 function cell(x:number,y:number,w:number,h:number,color:string){ctx!.fillStyle=color;ctx!.fillRect(x,y,w,h);ctx!.strokeStyle='#55717e';ctx!.lineWidth=2;ctx!.strokeRect(x,y,w,h);}
 cell(M,top,labelWidth,headerHeight,'#e3efdd');text('LUGAR DE ATENCIÓN',M+20,top+77,34,labelWidth-40,true);
 dates.forEach((date,i)=>{const x=M+labelWidth+i*cellWidth,saturday=new Date(date+'T12:00:00Z').getUTCDay()===6;cell(x,top,cellWidth,headerHeight,saturday?'#ddecf7':'#fff1cb');text(saturday?'SÁBADO':'DOMINGO',x+14,top+45,31,cellWidth-28,true);text(new Date(date+'T12:00:00Z').toLocaleDateString('es-AR',{day:'2-digit',month:'short',timeZone:'UTC'}),x+14,top+94,33,cellWidth-28,true);});
 places.forEach((place,n)=>{const y=top+headerHeight+n*rowHeight,size=Math.min(39,rowHeight/3.5);cell(M,y,labelWidth,rowHeight,'#e3efdd');lines(place.name,labelWidth-40,2,size,true).forEach((line,i)=>text(line,M+20,y+rowHeight/2-((size+8)/2)+i*(size+8),size,labelWidth-40,true));dates.forEach((date,i)=>{const x=M+labelWidth+i*cellWidth,saturday=new Date(date+'T12:00:00Z').getUTCDay()===6;cell(x,y,cellWidth,rowHeight,saturday?'#ddecf7':'#fff1cb');const items=trips.filter(t=>t.date===date&&t.place_id===place.id),assigned=items.flatMap(t=>t.people);const refs=noteBlocks.filter(b=>items.some(t=>t.id===b.id)).map(b=>'['+b.number+']').join(' ');const names=([refs,[...new Set(assigned)].join(' / ')].filter(Boolean).join(' '));const cellFont=Math.min(35,rowHeight/3.5),max=Math.max(1,Math.floor((rowHeight-22)/(cellFont+7)));lines(names||'—',cellWidth-24,max,cellFont).forEach((line,j)=>text(line,x+12,y+cellFont+14+j*(cellFont+7),cellFont,cellWidth-24));});});
 if(!places.length)text('No hay localidades para mostrar en este período.',M,top+headerHeight+110,40,W-2*M);
 if(noteBlocks.length){let y=top+headerHeight+places.length*rowHeight+53;text('OBSERVACIONES',M,y,35,W-2*M,true);y+=44;for(const block of noteBlocks){for(const line of block.lines){text(line,M,y,32,W-2*M);y+=39;}y+=12;}}
 text('Azul: sábado · Amarillo: domingo · [N] Observación al pie · … Nombre abreviado.',M,H-125,29,W-2*M);const weekdays=trips.filter(t=>!dates.includes(t.date)).length;text(weekdays?`${weekdays} atenciones de lunes a viernes: ver Calendario. Sus observaciones también figuran al pie.`:'Elegí una localidad para obtener una planilla con más detalle.',M,H-70,29,W-2*M);return canvas.toDataURL('image/jpeg',0.94);
}
